name: OG Productions
favicon: null
layout_spectrum: 0.17684916174039245
typography_spectrum: 0.32641929434612393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3294104519300163
  lightness: 0.2932975902222097
  saturation: 0.09462515148334205
  rhythmicContrast: 0.07480866461992264
purpose: []
